library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC_names <- readRDS("Source_Classification_Code.rds")
g<-group_by(NEI,year)
s<-summarise(g,total_emissions=sum(Emissions))
df<-data.frame(s)
plot(df$year,log(df$total_emissions),xlab="year",ylab = "total_emissions",ylim = c(15,16))
dev.copy(png,file="Plot1.png")
dev.off()